var RULES_YGO = [

{t:"Starting LP",s:"8000 each. Reach 0 = lose.",e:"Both players start with 8000 LP. When a player reaches 0 they lose immediately even mid-turn. Effect damage and battle damage both reduce LP."},
{t:"First Turn Rule",s:"First player skips Draw Phase and cannot enter Battle Phase.",e:"The player going first does NOT draw on their first turn and CANNOT enter the Battle Phase. This is absolute with no exceptions even from card effects."},
{t:"Normal Summon",s:"One per turn. Level 1-4 free. 5-6 needs 1 tribute. 7+ needs 2.",e:"Only 1 Normal Summon or Set per turn unless a card specifically grants more. Level 5-6 requires 1 Tribute. Level 7+ requires 2 Tributes. Tribute Summon uses your Normal Summon. Setting a monster also uses your Normal Summon."},
{t:"Hand Limit",s:"Max 6 cards at End Phase. No limit during turn.",e:"During the End Phase discard down to 6 cards. You choose which to discard. No hand size limit applies during the turn itself."},
{t:"Deck Requirements",s:"40-60 main deck. 0-15 extra. 0-15 side. Max 3 copies.",e:"Main Deck 40-60 cards. Extra Deck 0-15 Fusion/Synchro/Xyz/Link monsters. Side Deck 0-15 cards. Maximum 3 copies of any card with the same name across Main plus Side combined."},
{t:"Turn Structure",s:"Draw, Standby, Main 1, Battle, Main 2, End.",e:"Draw Phase: draw 1 card mandatory. Standby Phase: standby effects activate. Main Phase 1: summon and play cards. Battle Phase: optional, cannot be conducted on first turn by first player. Main Phase 2: optional, same as Main 1. End Phase: discard to hand limit."},

{t:"Spell Speed 1",s:"Normal Spells, Ignition Effects, Trigger Effects. Can only start a chain.",e:"Speed 1 effects can ONLY start a chain. They cannot be activated in response to anything. Normal Spells, Ritual Spells, Continuous Spells, Equip Spells, Field Spells, Ignition monster effects, and Trigger monster effects are all Speed 1. You must wait for an open game state to use them."},
{t:"Spell Speed 2",s:"Quick-Play Spells, Normal Traps, Quick Effects. Can chain to Speed 1 or 2.",e:"Speed 2 can be activated in response to Speed 1 or Speed 2 effects. Quick-Play Spells, Normal Traps, Continuous Traps, and monster Quick Effects are Speed 2. These can be activated during the opponent turn."},
{t:"Spell Speed 3",s:"Counter Traps only. ONLY other Counter Traps can respond.",e:"Counter Traps are the ONLY Speed 3 cards. Only other Counter Traps can chain to them. You cannot chain a Normal Trap or Quick-Play Spell to a Counter Trap. This is the only way to truly negate most spell and trap activations."},

{t:"Chain Resolution LIFO",s:"Last In First Out. Most recent effect resolves first.",e:"Chains always resolve in reverse order. Chain Link 2 resolves before Chain Link 1. Chain Link 3 before Chain Link 2. The last card added to a chain ALWAYS resolves first. This is the fundamental rule of chain resolution."},
{t:"MST vs Monster Reborn",s:"MST destroys but does NOT negate. Monster Reborn still resolves.",e:"If you activate Monster Reborn and opponent chains Mystical Space Typhoon to destroy it, Monster Reborn STILL resolves and the monster IS summoned. MST only destroys - it does NOT negate. Normal Spells do not need to remain on the field to resolve their effect. The activation placed the effect on the chain and it resolves regardless. To stop Monster Reborn you need a Counter Trap like Solemn Judgment or Solemn Strike."},
{t:"Destroying vs Negating on Chain",s:"Destroying a spell on chain does NOT stop its effect.",e:"Critical ruling: destroying a card and negating it are completely different. MST, Mystical Space Typhoon, Twin Twisters, and similar cards destroy but do NOT negate. A Normal Spell that is destroyed after activation still resolves its effect because the activation placed the effect on the chain. Only cards specifically stating negate the activation or negate the effect can stop an already-activated Normal Spell."},
{t:"Normal Spell Field Presence",s:"Normal Spells resolve even if destroyed after activation.",e:"Normal Spells do not need to remain on the field to resolve. Once a Normal Spell is activated and placed on the chain its effect will resolve even if the card is subsequently destroyed, banished, or removed. This differs from Continuous Spells and Equip Spells which DO require field presence."},
{t:"Continuous Spell Field Requirement",s:"Continuous Spells need to remain on field. If destroyed before resolving the effect disappears.",e:"Unlike Normal Spells, Continuous Spells and Equip Spells require the card to remain face-up on the field for their effect to apply. If a Continuous Spell is destroyed before its activation resolves it will not function. This is why Twin Twisters destroying a Continuous Spell does stop it."},
{t:"Chaining to Opponent Activation",s:"Chain Speed 2 or higher cards to any activation.",e:"When opponent activates a Spell or Trap you can chain any card or effect that is Spell Speed 2 or higher. Chaining does not automatically prevent the original card from resolving unless you specifically negate it."},
{t:"Open Game State",s:"When no chain is building both players can activate Speed 1 effects.",e:"An open game state occurs when the chain has fully resolved and both players have passed priority. In an open game state the turn player can activate Speed 1 effects. Outside an open game state only Speed 2 or higher effects can be activated."},
{t:"Priority",s:"Turn player activates first. Both players pass to advance phases.",e:"The turn player always has priority to activate effects first. Both players must pass priority consecutively for the game to advance to the next phase. After each effect activation both players can respond before the next resolution."},

{t:"Damage Step Restrictions",s:"Most cards CANNOT activate in Damage Step.",e:"During the Damage Step ONLY these may activate: Counter Traps, effects that directly modify ATK or DEF values, mandatory trigger effects, and cards specifically stating they can activate in the Damage Step. Cards that CANNOT activate include Torrential Tribute, Mirror Force, Book of Moon, Book of Eclipse, Compulsory Evacuation Device, and most hand traps."},
{t:"Damage Step Sub-Steps",s:"Start, Before Calc, Damage Calculation, After Calc, End.",e:"1. Start of Damage Step: face-down attacked monster flips face-up. 2. Before Damage Calculation: ATK/DEF modifiers activate here. 3. Damage Calculation: compare ATK/DEF, apply damage. 4. After Damage Calculation: when battles and destroys effects trigger. 5. End of Damage Step: destroyed monsters go to GY, FLIP effects activate."},
{t:"ATK/DEF Modifiers in Damage Step",s:"Cards that change ATK or DEF CAN activate in Damage Step.",e:"Cards and effects that directly change ATK or DEF values can be activated in the Damage Step. Examples that CAN activate: Rush Recklessly, Honest, Shrink, Forbidden Chalice, Mage Power. These specifically modify ATK/DEF so they are permitted."},
{t:"Hand Traps in Damage Step",s:"Most hand traps CANNOT activate in Damage Step.",e:"Effect Veiler, Ash Blossom and Joyous Spring, Nibiru the Primal Being, Infinite Impermanence, and most other hand traps CANNOT be activated during the Damage Step because they do not directly modify ATK/DEF. They are Speed 1 or their effect type is not permitted in the Damage Step."},
{t:"Cyber Dragon Sieger in Damage Step",s:"Sieger effect activates in Damage Step if it attacks a Machine.",e:"Cyber Dragon Sieger has an effect that can activate during the Damage Step because it directly modifies ATK values as part of its effect. Its effect to double ATK and gain ATK equal to opponent monster ATK is an ATK modification effect permitted in the Damage Step. Opponent cannot activate non-counter effects in response."},
{t:"Honest in Damage Step",s:"Honest can be activated in Damage Step to boost LIGHT monster ATK.",e:"Honest is a hand trap that can be activated during the Damage Step specifically because it modifies ATK. When a LIGHT monster attacks or is attacked you can return Honest from hand to give that monster ATK equal to the opponent monster ATK. This is one of the few hand traps permitted in the Damage Step."},

{t:"Negate Activation vs Negate Effect",s:"Negate activation stops card entirely. Negate effect nullifies but card stays.",e:"Negate the activation: card stopped completely and destroyed as if never played. Examples: Solemn Judgment, Solemn Strike, Dark Bribe. Negate the effect: card stays on field or resolves normally but effect is nullified. Examples: Effect Veiler, Infinite Impermanence, Skill Drain. Understanding this difference is critical for judge rulings."},
{t:"Solemn Judgment",s:"Counter Trap. Negate the activation of any monster summon, spell, or trap.",e:"Solemn Judgment negates the activation of any monster summon, spell card, or trap card and destroys it. Pay half your LP as cost. Since it negates activation, the card is treated as if it was never activated. A negated summon means the monster is sent to GY and was never properly summoned."},
{t:"Solemn Strike",s:"Counter Trap. Negate the activation of any effect that includes a monster summon.",e:"Solemn Strike negates and destroys any effect that includes a monster summon, or any monster effect. Pay 1500 LP. More flexible than Solemn Warning as it targets monster effects too."},
{t:"Ash Blossom and Joyous Spring",s:"Hand trap. Negate effects that search, draw from deck, or special summon from deck.",e:"Ash Blossom is a Speed 2 Quick Effect hand trap. Discard it to negate any effect that searches the deck, draws from deck, or special summons from deck. Cannot be used in the Damage Step. Can be chained to Speed 1 effects. One of the most commonly used hand traps in competitive play."},
{t:"Effect Veiler",s:"Hand trap. Negate a face-up monster effect during opponent main phase.",e:"Discard Effect Veiler during opponent Main Phase to negate the effects of one opponent face-up monster until end of turn. This is a Speed 1 effect so it can only be activated in an open game state during the Main Phase, not during the Battle Phase or in response to another effect activation."},
{t:"Infinite Impermanence",s:"Trap. Negate a monster effect. If activated from hand negates row.",e:"Infinite Impermanence negates the effects of one face-up monster the opponent controls. If activated from hand while you control no cards it also negates all Spell and Trap effects in the same column for the rest of the turn. This is a powerful disruption tool."},
{t:"Skill Drain",s:"Continuous Trap. Negates all face-up monster effects on field.",e:"While Skill Drain is face-up on the field, the effects of all face-up monsters on the field are negated. This is a continuous negation effect that affects both players. Monsters with effects that apply while in the GY or hand are not affected."},

{t:"Targeting Rules",s:"Effects using target must declare targets at activation.",e:"A targeting effect uses the word target in its text. Targets must be declared when the effect is activated. If a target becomes illegal before the effect resolves the effect has no result for that target. If ALL targets become invalid before resolution the effect resolves without effect."},
{t:"Cannot Be Targeted",s:"Targeting protection does not stop non-targeting effects.",e:"Monsters that cannot be targeted by card effects are still vulnerable to non-targeting effects. Destroy all monsters, each monster you control gets minus 2000 ATK, and similar blanket effects are not targeting effects. Only effects specifically using the word target are stopped by targeting protection."},
{t:"Destruction Protection",s:"Cannot be destroyed does not prevent removal by other means.",e:"Monsters that cannot be destroyed by card effects can still be removed by: banishing, returning to hand or deck, being used as Fusion/Synchro/Xyz/Link material, being tributed, being flipped face-down then destroyed. Only effects that specifically destroy are prevented."},

{t:"Costs vs Effects Semicolon Rule",s:"Text before semicolon is cost. Paid at activation. Never refunded.",e:"The text before the semicolon is the COST and is paid immediately when the effect is activated before the chain fully builds. Discard 1 card: draw 2 cards means the discard is paid at activation. If the effect is later negated the cost is NOT returned. LP paid, cards discarded, and monsters tributed as costs are permanently spent."},
{t:"Activation Costs Are Mandatory",s:"If you activate an effect you must pay its cost.",e:"If you choose to activate an effect you must be able to pay its full cost and must pay it. You cannot activate an effect if you cannot pay the cost. Once activated the cost cannot be reduced or changed."},

{t:"Proper Summon Requirement",s:"Extra Deck monsters must be properly summoned before revival.",e:"Extra Deck monsters including Fusion, Synchro, Xyz, and Link monsters that were never properly summoned cannot be revived from the GY or banished zone by effects like Monster Reborn. If a Synchro Monster was sent from the Extra Deck to the GY without being properly Synchro Summoned it cannot be targeted by Monster Reborn."},
{t:"Synchro Summon Formula",s:"Tuner Level plus Non-Tuner Levels must equal Synchro Level exactly.",e:"Send 1 Tuner monster plus 1 or more non-Tuner monsters from your field to the GY. Their combined Levels must equal EXACTLY the Synchro Monster Level. Not more, not less. Example: Level 3 Tuner plus Level 5 Non-Tuner equals Level 8 Synchro."},
{t:"Xyz Summon Materials",s:"2 or more same-Level monsters. Materials are not on field.",e:"Overlay 2 or more monsters of the same Level. They become Xyz Materials underneath the Xyz Monster. Materials are NOT on the field. They cannot be targeted by most card effects. When the Xyz Monster leaves the field all remaining materials go to the GY. Detaching a material as cost sends it to the GY."},
{t:"Link Summon Rules",s:"Pay materials as listed. Link Rating equals number of materials used.",e:"Send the required number and type of monsters to the GY as Link Materials. Link Monsters have NO DEF value and cannot be in Defense Position. Link Rating equals the number of materials required. A Link-2 used as material counts as 2 materials toward another Link Summon."},
{t:"Link Arrows and Extra Deck Zones",s:"Extra Deck monsters need Extra Monster Zone or zone pointed to by Link Arrow.",e:"After the 2017 Master Rule, Fusion, Synchro, and Xyz monsters from the Extra Deck can only be summoned to the Extra Monster Zone or a Main Monster Zone that a Link Monster Arrow points to. Without a Link Monster on field you are limited to 1 Extra Deck monster at a time occupying the Extra Monster Zone."},
{t:"Pendulum Scale Summon",s:"Summon Levels strictly BETWEEN the two Scale values.",e:"Place Pendulum Monsters in leftmost and rightmost Spell/Trap Zones as Pendulum Scales. You can Pendulum Summon any number of monsters from hand and face-up Extra Deck whose Levels fall strictly BETWEEN the two Scale numbers. Scale 1 and Scale 8 allows Level 2, 3, 4, 5, 6, 7. When Pendulum Monsters are destroyed on the field they go face-up to the Extra Deck instead of the GY."},
{t:"Fusion Summon Materials",s:"Send listed materials from hand and field to GY. Use Polymerization or Fusion effect.",e:"Activate Polymerization or a card with a Fusion effect. Send the Fusion Materials listed on the Fusion Monster from hand and/or field to the GY. Material requirements must be met exactly. Some cards like Miracle Fusion allow using GY materials. Contact Fusion like Gladiator Beasts requires no spell."},
{t:"Ritual Summon Process",s:"Activate Ritual Spell. Tribute Levels equal to or exceeding Ritual Monster Level.",e:"Activate the appropriate Ritual Spell card. Tribute monsters from hand or field with total Levels equal to or exceeding the Ritual Monster Level. Over-tributing is allowed. The Ritual Monster must be in your hand. You can tribute from both hand and field simultaneously."},
{t:"Pendulum Monsters in GY",s:"Pendulum Monsters go face-up to Extra Deck when destroyed on field.",e:"When a Pendulum Monster is destroyed while face-up on the field, instead of going to the GY it goes face-up to the Extra Deck. This allows it to be Pendulum Summoned again later. However if a Pendulum Monster is sent to the GY as a cost or by a non-destruction effect it does go to the actual GY."},

{t:"SEGOC",s:"Turn Player places effects first then Non-Turn Player. Resolves LIFO.",e:"SEGOC stands for Simultaneous Effects Go On Chain. When multiple trigger effects activate from the same event at the same time, the Turn Player chooses the order to place their effects on the chain first, then the Non-Turn Player places their effects. The chain then resolves LIFO. Mandatory effects must be placed. Optional effects can be declined."},
{t:"If vs When Timing",s:"When-you-can CAN miss timing. If-you-can CANNOT miss timing.",e:"Optional When trigger effects can miss their timing if their trigger condition was not the last thing to resolve in a chain or sequence of events. Optional If trigger effects cannot miss timing and will always activate when their condition is met regardless of what else happened. Mandatory effects never miss timing. Example: When this card is sent to GY you can draw 1 card - this can miss timing if the send was not the last thing to happen."},
{t:"Missing the Timing Example",s:"Send to GY as part of cost can cause optional When effects to miss timing.",e:"If a card says send 1 monster to GY then draw 1 card, and the sent monster has a When optional trigger, that trigger MISSES TIMING because drawing was the last thing to happen, not the sending. If the monster instead says If this card is sent to GY you can draw, the If trigger CANNOT miss and will activate."},

{t:"Destruction vs Other Removal",s:"Tributed, used as material, or sent to GY as cost is NOT destruction.",e:"A monster is destroyed only by battle or by an effect specifically using the word destroy. Being tributed, being used as Synchro/Xyz/Link material, being sent to the GY as the cost of an effect, or being returned to hand/deck is NOT destruction. These methods do not trigger when destroyed effects."},
{t:"Battle Destruction",s:"Monster with lower ATK attacking higher ATK monster is destroyed.",e:"When a monster in ATK position attacks a monster with higher ATK, the attacking monster is destroyed by battle and its controller takes battle damage equal to the ATK difference. The defending monster is not destroyed. When two monsters with equal ATK battle both are destroyed."},
{t:"Battle Damage Formula",s:"Attacker ATK minus Defender ATK equals battle damage to losing player.",e:"ATK vs ATK: the player whose monster has lower ATK takes damage equal to the difference. Equal ATK: both monsters destroyed, no damage. ATK vs DEF: if attacker ATK exceeds defender DEF, defending monster destroyed, NO damage unless piercing. Piercing damage formula: attacker ATK minus defender DEF equals damage dealt."},
{t:"Direct Attack",s:"If opponent has no monsters you can attack directly for full ATK damage.",e:"When your opponent controls no monsters you can attack directly. Your monster deals its full ATK as battle damage to the opponent. Some monster effects allow direct attacks even when opponent has monsters - in that case the attacking monster often has reduced ATK for damage calculation purposes as stated on the card."},

{t:"Continuous Effects Always On",s:"Continuous effects are always active while face-up. No activation needed.",e:"Continuous effects apply automatically while the card is face-up on the field. They do not use the chain and cannot be responded to as an activation. If the card leaves the field the effect ends immediately even mid-chain resolution."},
{t:"Replacement Effects",s:"Instead effects replace how an event happens. Not placed on chain.",e:"Replacement effects use the word instead and modify how an event happens before it occurs. They are not placed on the chain. When multiple replacement effects apply to the same event the controller of the card being affected chooses the order to apply them."},
{t:"Win Conditions",s:"LP to 0, deck out, Exodia, Destiny Board, other card-specific wins.",e:"Primary: LP reaches 0. Deck out: cannot draw on mandatory Draw Phase. Exodia: all 5 Exodia pieces in hand simultaneously. Destiny Board: spell out F-I-N-A-L over 5 Standby Phases. Ghostrick Angel: attach 10 Xyz Materials. Jackpot 7: banish all 3 copies from GY. Final Countdown: survive 20 turns."},

{t:"Gemini Monsters",s:"Treated as Normal on field/GY. Second Normal Summon grants effects.",e:"Gemini Monsters are treated as Normal Monsters while on the field or in the GY. Using your Normal Summon on a face-up Gemini Monster already on the field (Gemini Summon) grants it its effects and makes it an Effect Monster. If it leaves the field it reverts to Normal Monster status."},
{t:"Spirit Monsters",s:"Cannot be Special Summoned normally. Return to hand during End Phase.",e:"Spirit Monsters cannot be Special Summoned by normal means. During the End Phase of the turn they were Normal or Flip Summoned they return to the owner hand. This return is mandatory not optional."},
{t:"FLIP Effects",s:"Activate when flipped face-up by attack, Flip Summon, or card effect.",e:"FLIP effects are Speed 1 trigger effects that activate when the monster is flipped face-up. If attacked and destroyed before being flipped, FLIP does not activate. If flipped face-up by attack, FLIP activates at End of Damage Step. If flipped by card effect, FLIP activates at next available window."},
{t:"Toon Monsters",s:"Require Toon World. Cannot attack turn summoned. Can attack directly if no opposing Toons.",e:"Most Toon Monsters require Toon World on the field to be summoned or attack. Cannot attack on the turn they are summoned. May attack opponent directly if opponent controls no Toon Monsters. If opponent controls a Toon Monster, must attack it instead."},

{t:"Forbidden and Limited List",s:"Forbidden = 0 copies. Limited = 1 copy. Semi-Limited = 2 copies.",e:"Konami updates the F&L list regularly. Forbidden cards: 0 copies allowed. Limited: 1 copy across Main Deck plus Side Deck combined. Semi-Limited: 2 copies across Main plus Side. Unlimited (not on list): 3 copies maximum. Always verify current list before tournament play."},

{t:"Trap Card Set Rule",s:"Traps must be Set first. Cannot activate same turn they were Set.",e:"All Trap cards must be Set face-down on the field before they can be activated. A Trap Set this turn cannot be activated until the opponent next turn at the earliest. This is called the 1-turn set rule. Quick-Play Spells Set on your own turn also cannot be activated until opponent turn or your next turn."},

{t:"Nibiru the Primal Being",s:"Can be activated after opponent 5th summon. Tributes all monsters.",e:"During the Main Phase after opponent Special Summons their 5th or more monster, you can Special Summon Nibiru from hand by tributing all monsters on the field. Cannot be used in the Damage Step. This is one of the strongest hand traps for stopping combo decks."},
{t:"Called by the Grave",s:"Banish monster from GY to negate effects of same-name monsters.",e:"Banish 1 monster from opponent GY and until end of turn negate the effects of all monsters with that name the opponent controls and prevents them from activating. Powerful against decks that rely on GY effects or hand traps."},
{t:"Ghost Ogre and Snow Rabbit",s:"Hand trap. Destroy a monster or spell/trap when its effect activates.",e:"When a monster on the field or spell/trap activates its effect, discard Ghost Ogre to destroy it. This is a Speed 2 Quick Effect. Cannot destroy during the Damage Step. Targets cards that have already activated their effects."}
];
