var RULES_GUNDAM = [
{t:"Win Conditions",s:"Reduce opponent Base to 0 HP or destroy their Flagship.",e:"Win by reducing the opponent Base to 0 HP through combat damage, or by destroying the opponent Flagship unit. Base starts at 10 HP. When Base reaches 0 that player loses immediately."},
{t:"Turn Structure",s:"Draw, gain resource, Main Phase, Battle Phase, End Phase.",e:"Draw Phase: draw 1 card. Resource Phase: gain 1 resource up to your Flagship maximum. Main Phase: deploy units by paying resource cost, play Burst cards, activate abilities. Battle Phase: declare attackers, each unit may attack once per turn. End Phase: resolve end of turn effects. First player CANNOT attack on their first turn."},
{t:"Resource System",s:"Gain 1 resource per turn up to Flagship maximum. Resources carry over.",e:"At the start of each turn gain 1 resource. Your Flagship determines the maximum resources you can hold. Unspent resources carry over to the next turn up to your maximum. High-cost units require saving resources across turns. Managing resource accumulation is the core strategic element."},
{t:"Deploying Units",s:"Pay resource cost. Enter REST position. Cannot attack until next turn unless RUSH.",e:"Play units from hand by paying their resource cost in resources. Units enter the field in REST position (turned sideways). They cannot attack on the turn they are deployed unless they have the RUSH keyword. Maximum 5 units on the field at one time not counting the Flagship."},
{t:"Battle System",s:"Attacker Power vs Defender HP. Excess Power becomes Penetrating Damage to Base.",e:"When a unit attacks a blocking unit: compare attacker Power against defender HP. If Power is equal to or greater than HP, defender is destroyed. The difference (Power minus HP) is called Penetrating Damage and is immediately applied to the defending player Base. If no blocker: the full Power of the attacking unit hits the Base as direct damage."},
{t:"Penetrating Damage",s:"Excess Power after destroying blocker carries through to hit Base.",e:"Penetrating Damage is the amount of damage that carries through to the Base after a blocker is destroyed. Formula: attacker Power minus defender HP equals Penetrating Damage. Example: 3000 Power attacks 1500 HP blocker. Blocker destroyed AND 1500 Penetrating Damage hits the Base. High Power units are especially dangerous because of this mechanic."},
{t:"RUSH Keyword",s:"Unit can attack the turn it is deployed.",e:"Units with RUSH bypass the standard restriction that newly deployed units cannot attack. A RUSH unit can attack immediately on the same turn it enters the field. RUSH is critical for aggressive strategies and for finishing games before opponent can establish defenses."},
{t:"BLOCKER Keyword",s:"Can intercept any attack targeting Base or other units.",e:"When an opponent declares an attack, you may switch a unit with BLOCKER from ACTIVE to REST position to intercept it. The BLOCKER becomes the new attack target. The attacker must fight the BLOCKER instead of the original target. A unit can only use BLOCKER once per turn and must be in ACTIVE position to do so."},
{t:"Burst Cards",s:"Can be played at any time during either player turn including response to attacks.",e:"Burst cards are marked with a lightning bolt symbol. They can be activated at any time during either player turn: during Main Phase, in response to attack declarations, in response to effects. This makes them function like Quick-Play Spells in Yu-Gi-Oh or Instants in Magic. Pay their resource cost when activated."},
{t:"Flagship Rules",s:"In Command Zone. Destroyed means lose. Determines color identity.",e:"Your Flagship is placed in the Command Zone before play begins. It determines which card colors you can include in your deck. Flagship has unique abilities that often define your strategy. If your Flagship is destroyed at any point you immediately lose the game. Most effects cannot target Flagships unless specifically stated."},
{t:"Ace Units",s:"Extremely powerful units. Only 1 Ace unit per deck total.",e:"Ace units are the most powerful cards in the game with highest stats and abilities. Only 1 Ace unit of any name may be included per deck. They typically require meeting level or other requirements to deploy. Their power justifies the strict 1 per deck limitation."},
{t:"REST and ACTIVE Positions",s:"REST equals tapped. ACTIVE equals untapped. Attack puts units in REST.",e:"Units in ACTIVE position (upright) can attack and use BLOCKER. After attacking, blocking, or being used as a cost, units move to REST position (turned sideways). Units become ACTIVE again during an unsuspend step or specific card effects. REST units cannot attack or use BLOCKER."},
{t:"Color Identity",s:"Cards must match Flagship color. Multi-color Flagships allow both colors.",e:"Your Flagship color or colors determines what cards you can include in your deck. All cards must match your Flagship color identity. Dual-color Flagships allow cards of either color. Colorless cards can go in any deck."}
];
