var RULES_DIG = [
{t:"Win Condition",s:"Break all 5 Security then land an unblocked direct attack.",e:"Each player starts with 5 face-down Security cards. Win by breaking all opponent Security cards reducing their Security to 0, then landing an unblocked direct attack on the player. You can also win if opponent cannot draw when required."},
{t:"Memory Gauge",s:"Shared minus 3 to plus 3. Crosses to opponent side means their turn starts immediately.",e:"The Memory Gauge runs from minus 3 (opponent side) to plus 3 (your side). When you play cards or use effects you spend memory which moves the gauge toward the opponent. When the gauge moves to 1 or more on the opponent side after any action the current player turn ends immediately and the opponent turn begins."},
{t:"Turn Structure",s:"Unsuspend, Draw, Breeding, Main Phase, End.",e:"Unsuspend Phase: all your suspended Digimon become unsuspended. Draw Phase: draw 1 card. Breeding Phase: if Digimon in Breeding Zone has 3 or more DP you may move it to the battle area. Main Phase: play cards, digivolve, attack, use effects. End Phase: resolve end of turn effects."},
{t:"Digivolving Rules",s:"Pay digivolve cost. Stack on compatible target. Inherit all effects underneath.",e:"To digivolve pay the digivolve cost listed on the card and place it on top of a compatible target Digimon meeting the Digivolves From requirement (matching name or Level). The new Digimon retains all cards underneath it and their Inherited Effects are active. Digivolution removes Suspension allowing the Digimon to attack again."},
{t:"Battle Resolution",s:"Compare DP values. Higher DP wins. Equal DP means both are deleted.",e:"When two Digimon battle compare their DP values. Higher DP Digimon wins and the lower DP Digimon is deleted. If both have equal DP both are deleted simultaneously. Deleted Digimon and all cards underneath them are sent to the Trash. Delete effects and On Deletion triggers activate at this time."},
{t:"Security Check",s:"Reveal top Security card. Tamer and Option security effects activate. Then discard.",e:"When an unblocked attack reaches Security, reveal the top Security card. If it is a Tamer or Option (Spell) card its Security effect activates and resolves. Digimon Security cards with a Security effect text also activate. After the effect resolves (or if there is no security effect) the Security card is discarded."},
{t:"BLOCKER Keyword",s:"Can intercept any attack targeting player or another Digimon.",e:"When an attack is declared against any target, you may declare a Digimon with BLOCKER as the blocker. Switch that Digimon to REST position. The attack is redirected to the BLOCKER and battle is resolved between attacker and blocker. A Digimon can only use BLOCKER once per turn."},
{t:"Inherited Effects",s:"Effects of cards underneath active Digimon are active while on field.",e:"When a Digimon has digivolved multiple times, all the cards underneath it (the digivolve sources) provide their Inherited Effects to the currently active Digimon. All these Inherited Effects are active simultaneously as long as those cards remain underneath that Digimon on the field."},
{t:"Trash Zone",s:"Deleted Digimon and used Options go here. Like a graveyard.",e:"The Trash is the discard pile equivalent. Deleted Digimon (along with all cards underneath), used Option cards, and other discarded cards go here. Some card effects interact with Trash. Trash is public information - both players may look at it at any time."},
{t:"Tamer Cards",s:"Pay memory cost to place on field. Provide ongoing effects.",e:"Tamer cards represent human partners. Pay their memory cost to place them on the field. They provide continuous or triggered effects. Tamers generally cannot be attacked directly and do not participate in battle. They often have Security effects that activate when revealed from Security."},
{t:"Option Cards",s:"One-time effect cards paid with memory. Go to Trash after use.",e:"Option cards are one-time effects paid with memory that go to the Trash after resolving. They are equivalent to Spell cards in other TCGs. Many Option cards have Security effects. Option cards can generally be played any time during your Main Phase."},
{t:"Suspension System",s:"Attacking Digimon becomes Suspended. Unsuspend at start of your turn.",e:"When a Digimon attacks it becomes Suspended (turned sideways). Suspended Digimon cannot attack or block. At the beginning of your Unsuspend Phase all your Suspended Digimon become Unsuspended simultaneously. Digivolving also Unsuspends a Digimon. Some effects can Suspend Digimon outside of normal attack resolution."},
{t:"Deck Construction",s:"50 card main deck. 0-5 Digi-Egg cards. Max 4 copies per card number.",e:"Main Deck must contain exactly 50 cards. Digi-Egg Deck can contain 0-5 Digi-Egg cards. Maximum 4 copies of any card with the same card number. Different printings or alternate art of the same card with different card numbers count separately."}
];
