var MTG_RULES = [
// ============================================================
// GAME STRUCTURE
// ============================================================
{q:"How do you win in MTG?",a:"Reduce your opponent's life total to 0, force them to draw from an empty library, give them 10 poison counters, or meet a card's special win condition (e.g. Thassa's Oracle, Felidar Sovereign). Starting life: 20 (Standard/Modern/Legacy/Vintage/Pioneer/Draft), 40 (Commander)."},
{q:"What are the phases of a turn?",a:"Beginning Phase (Untap, Upkeep, Draw), Main Phase 1, Combat Phase (Beginning of Combat, Declare Attackers, Declare Blockers, Combat Damage, End of Combat), Main Phase 2, Ending Phase (End Step, Cleanup). Sorceries, creatures, and most permanents can only be cast during your main phase when the stack is empty."},
{q:"What is priority?",a:"Priority determines who can cast spells or activate abilities. Active player gets priority first in each step/phase. After any player takes an action, the active player gets priority again. Both players must pass priority on an empty stack to move to the next step/phase."},
{q:"What is the stack?",a:"The stack is the zone where spells and abilities wait to resolve. Last-in first-out order — the most recently added spell/ability resolves first. After each resolution, players get priority again before the next item resolves."},
{q:"Can you cast spells at instant speed?",a:"Instants and abilities with flash can be cast any time you have priority. Sorceries, creatures, enchantments, artifacts, and planeswalkers can only be cast during your main phase when the stack is empty and you have priority."},

// ============================================================
// COMBAT
// ============================================================
{q:"How does combat damage work?",a:"Attacking creatures deal damage equal to their power to the creature blocking them (or the player/planeswalker if unblocked). Blockers deal damage equal to their power back to the attacker. Damage is assigned simultaneously unless a creature has first strike or double strike."},
{q:"What is first strike and double strike?",a:"First strike: deals combat damage in a special first combat damage step before normal damage. Creatures that die to first strike damage don't deal combat damage back. Double strike: deals damage in both the first strike step AND the normal combat damage step."},
{q:"Can a blocked creature still deal damage to the player?",a:"No. Once a creature is blocked, it deals damage to the blocking creature(s) even if the blocker is removed before damage. A creature only deals damage to the defending player if it is unblocked — or if it has trample."},
{q:"How does trample work?",a:"A trampling attacker must assign lethal damage to each blocker first, then any excess damage goes to the defending player or planeswalker. 'Lethal damage' means damage equal to the blocker's toughness (or 1 if it has deathtouch). If a blocker has protection, trample damage still tramples through."},
{q:"How does deathtouch work?",a:"Any amount of damage dealt by a creature with deathtouch is considered lethal. A 1/1 with deathtouch can kill a 10/10. When assigning trample damage with deathtouch, only 1 damage needs to be assigned to each blocker to be considered lethal, and the rest can trample through."},
{q:"Can you attack planeswalkers?",a:"Yes. When declaring attackers, you can choose to attack a planeswalker an opponent controls instead of the player. Damage dealt to a planeswalker removes that many loyalty counters. A planeswalker with 0 loyalty is put into the graveyard as a state-based action."},
{q:"What is vigilance?",a:"A creature with vigilance doesn't tap when it attacks. It can still block on the following turn."},
{q:"What is menace?",a:"A creature with menace can only be blocked by two or more creatures. If the defending player can't or doesn't block it with at least two creatures, it's unblocked."},
{q:"What is reach?",a:"A creature with reach can block creatures with flying, as if it had flying itself. It doesn't gain the ability to attack as though it had flying."},
{q:"What is lifelink?",a:"Damage dealt by a creature with lifelink causes its controller to gain that much life simultaneously with the damage being dealt. Multiple instances of lifelink don't cause you to gain life twice."},
{q:"What is indestructible?",a:"A permanent with indestructible can't be destroyed by damage or by effects that say 'destroy.' It CAN be killed by -X/-X effects that reduce toughness to 0, by exile effects, by sacrifice, or by being bounced."},
{q:"What is hexproof?",a:"A permanent with hexproof can't be the target of spells or abilities your opponents control. It can still be targeted by its controller's effects, and it can be affected by spells that don't target (like Wrath of God)."},
{q:"What is shroud?",a:"A permanent with shroud can't be the target of ANY spells or abilities — including those controlled by its own controller. Unlike hexproof, the controller can't target it either."},
{q:"What is protection?",a:"Protection from [quality] means: can't be Damaged, Enchanted/Equipped, Blocked, or Targeted (DEBT) by sources with that quality. Protection from red means a creature can't be targeted by red spells, can't be blocked by red creatures, etc."},

// ============================================================
// STATE-BASED ACTIONS
// ============================================================
{q:"What are state-based actions?",a:"State-based actions (SBAs) are rules checked continuously. They include: creatures with 0 or less toughness die, creatures with lethal damage die, players with 0 or less life lose, players with 10+ poison counters lose, legend rule, planeswalkers with 0 loyalty die. SBAs are checked before any player gets priority."},
{q:"What is the legend rule?",a:"If a player controls two or more legendary permanents with the same name, that player chooses one to keep and puts the rest in the graveyard as a state-based action. This also applies to Legendary creatures, planeswalkers, etc."},
{q:"When do creatures die from damage?",a:"Damage is marked on creatures. At the end of each turn, damage is removed. Lethal damage (damage >= toughness) causes a creature to die as a state-based action, checked immediately. A creature with regeneration can replace its death once per turn."},

// ============================================================
// COMMANDER FORMAT
// ============================================================
{q:"What is Commander damage?",a:"In Commander, if a single commander deals 21 or more combat damage to a player over the course of the game, that player loses. This only counts combat damage from that commander, even if it changes zones. It accumulates across the whole game."},
{q:"What is the Commander tax?",a:"Each time a commander is cast from the Command Zone, it costs 2 more mana for each previous time it's been cast from the Command Zone this game. This applies even if it was countered. Casting from hand, graveyard, or exile does not add to or cost the tax."},
{q:"Can you put a commander in the graveyard?",a:"When your commander would go to the graveyard or exile from anywhere, you may choose to put it in the Command Zone instead. This is a replacement effect — you choose when the event would happen, not after."},
{q:"What happens if two players have the same commander?",a:"Both players can play the same commander. The legend rule only applies within a single player's permanents — you can each have your commander on the battlefield at the same time."},
{q:"Can you use your commander as a commander if it's not legendary?",a:"Commanders must be legendary creatures, or specifically state they can be your commander. Some planeswalkers and non-legendary creatures (like those with 'This can be your commander') are also legal commanders."},
{q:"What is partner in Commander?",a:"Two creatures with the Partner keyword can both be your commanders. You start with both in the command zone, your deck can include cards of both their colors, and both commanders start with 0 commander damage."},
{q:"What is a Saga?",a:"Sagas enter the battlefield with a lore counter. At the beginning of your precombat main phase, you add a lore counter and trigger the ability of the chapter matching the new total. When the final chapter triggers, you sacrifice the Saga after the ability resolves."},

// ============================================================
// KEYWORDS & MECHANICS
// ============================================================
{q:"What is flash?",a:"A permanent spell with flash can be cast any time you could cast an instant — during any player's turn, in response to other spells, etc. Flash doesn't affect the permanent's abilities once it enters the battlefield."},
{q:"What is haste?",a:"A creature with haste can attack and use tap abilities the turn it enters the battlefield. Normally, creatures have 'summoning sickness' and can't attack or tap until you've controlled them since the beginning of your most recent turn."},
{q:"What is flying?",a:"A creature with flying can only be blocked by creatures with flying or reach. It can still attack and be targeted normally. Flying doesn't affect the creature outside of combat (e.g. it can be hit by spells without flying restriction)."},
{q:"What is convoke?",a:"Convoke lets you tap creatures you control to help pay for a spell. Each tapped creature reduces the cost by 1 generic mana or one mana of that creature's color. You can tap creatures of any color to pay generic mana."},
{q:"What is kicker?",a:"Kicker is an optional additional cost you may pay when casting a spell. If you pay the kicker cost, the spell has additional effects as described. You decide whether to pay kicker when you begin casting the spell."},
{q:"What is cycling?",a:"Cycling is an activated ability you can use any time you could cast an instant. Pay the cycling cost, discard the card, draw a card. Some cards have abilities that trigger when you cycle them."},
{q:"What is escape?",a:"Escape lets you cast a card from your graveyard by paying the escape cost and exiling a number of other cards from your graveyard. The card is still cast — it can be countered, and it uses the stack."},
{q:"What is foretell?",a:"Foretell lets you exile a card from your hand face-down during your turn by paying 2 mana. On future turns, you can cast the exiled card for its foretell cost, usually cheaper than its normal cost."},
{q:"What is adventure?",a:"An Adventure card has two halves — the creature half and the adventure (instant/sorcery) half. You can cast the adventure first (it exiles), then later cast the creature from exile. If countered, it goes to the graveyard, not exile."},
{q:"What is mutate?",a:"Mutate lets you cast a creature under or over a non-Human creature you control. The merged permanent has all abilities of all components. The 'mutated creature' uses the power/toughness and name of the top card, but has all abilities from all cards in the pile."},
{q:"What is learn?",a:"Learn lets you either reveal a Lesson card from outside the game and put it in your hand, or discard a card and draw a card. In tournament play, the 'outside the game' cards come from your sideboard."},
{q:"What is ward?",a:"Ward is a triggered ability. When the permanent with ward becomes the target of a spell or ability an opponent controls, that player must pay the ward cost or the spell/ability is countered. Ward doesn't prevent the targeting, only counters after the fact."},
{q:"What is demonstrate?",a:"Demonstrate is a keyword on some instants and sorceries. When you cast a spell with demonstrate, you may copy it. If you do, an opponent of your choice also gets a copy. You choose targets for your copy; the opponent chooses targets for theirs."},
{q:"What is casualty?",a:"Casualty N is an optional additional cost. As you cast the spell, sacrifice a creature with power N or greater. If you do, you copy the spell. The copy has no targets unless the original had targets."},
{q:"What is suspect?",a:"A suspected creature has menace and can't block. When a creature becomes suspected, that status lasts until it leaves the battlefield or becomes unsuspected."},

// ============================================================
// TRIGGERED & ACTIVATED ABILITIES
// ============================================================
{q:"What is the difference between triggered and activated abilities?",a:"Triggered abilities use 'when,' 'whenever,' or 'at' — they trigger automatically when their condition is met and go on the stack. Activated abilities use [cost]:[effect] — you must pay the cost to activate them. Either can be activated/triggered at instant speed unless specified."},
{q:"Can you respond to a triggered ability?",a:"Yes. When a triggered ability goes on the stack, all players get priority before it resolves. You can cast instants or activate abilities in response. The trigger will resolve after all responses resolve."},
{q:"What is an enters the battlefield trigger?",a:"An 'enters the battlefield' (ETB) trigger happens when a permanent enters the battlefield. It goes on the stack the next time any player would receive priority. Even if the permanent dies before priority is received, the trigger still goes on the stack."},
{q:"Can you activate a planeswalker loyalty ability multiple times?",a:"No. You can activate only one loyalty ability per planeswalker per turn, and only during your main phase when the stack is empty. The +/- loyalty is part of the cost, not the effect."},

// ============================================================
// COUNTERS & TOKENS
// ============================================================
{q:"How do +1/+1 and -1/-1 counters interact?",a:"+1/+1 and -1/-1 counters on the same creature annihilate each other as a state-based action. For every +1/+1 counter, remove one of each type. They cannot coexist on the same permanent."},
{q:"What are tokens?",a:"Tokens are permanents created by spell and ability effects. They exist only on the battlefield — they can't go to any zone other than the battlefield (they cease to exist in any other zone). They can't be returned from the graveyard."},
{q:"Do tokens die?",a:"Yes. Tokens can be destroyed, sacrificed, or die from damage. When a token would go to the graveyard or any zone other than the battlefield, it ceases to exist instead, but 'dies' and 'leaves the battlefield' triggers still happen."},

// ============================================================
// MANA & COSTS
// ============================================================
{q:"What is split second?",a:"While a spell with split second is on the stack, players can't cast other spells or activate non-mana abilities. Triggered abilities still trigger and go on the stack. Mana abilities can still be activated."},
{q:"Can you tap lands for mana at any time?",a:"Mana abilities (tapping a land for mana, etc.) can be activated any time you could cast an instant, as well as at any time you need to pay a cost. They don't use the stack and can't be responded to."},
{q:"What is Phyrexian mana?",a:"A Phyrexian mana symbol (e.g. {W/P}) can be paid with one mana of the appropriate color OR by paying 2 life. Cards with Phyrexian mana can be cast for life even if you don't have the right colors of mana."},
{q:"What is a copy of a spell?",a:"A copy of a spell is put directly on the stack — it is not cast. Copies don't trigger 'whenever you cast' effects. You can choose new targets for a copy. A copy of a permanent spell becomes a token if it resolves."},
{q:"What is an additional cost?",a:"Additional costs like kicker or sacrifice costs are paid as part of casting the spell. They are different from alternative costs (like flashback). You can only pay one alternative cost, but you can pay multiple additional costs."},

// ============================================================
// ZONES
// ============================================================
{q:"What is the exile zone?",a:"The exile zone is a public zone where cards are removed from the game. Exiled cards can interact with other cards only if a card specifically refers to cards in exile. Exiling is different from destroying — destroyed cards can be regenerated or indestructible, exiled cards cannot."},
{q:"What is the graveyard?",a:"The graveyard is where permanents go when they're destroyed, sacrificed, or discarded, and where spells go after they resolve. It's a public zone. Many cards interact with graveyards — reanimation, flashback, escape, etc."},
{q:"Can you look at face-down cards?",a:"You can look at your own face-down cards (morph, manifest, foretell) at any time. Opponents can look at them when they leave the battlefield or when they're turned face-up. The act of looking doesn't turn them face-up."},

// ============================================================
// SPECIFIC COMMON RULES
// ============================================================
{q:"Does counterspelling a spell prevent its effects?",a:"Yes. A countered spell never resolves — its effects don't happen, and it goes to the graveyard. A countered permanent spell doesn't enter the battlefield. However, 'when you cast' triggers already went on the stack before the spell was countered."},
{q:"Can you counter a spell with no target?",a:"Yes. You can counter any spell with a counterspell that says 'counter target spell,' regardless of whether the spell has targets. A spell without targets can still be countered."},
{q:"What is 'dies' versus 'is destroyed'?",a:"'Dies' means goes from the battlefield to the graveyard for any reason — destruction, lethal damage, sacrifice, etc. 'Is destroyed' specifically means destruction effects (destroy spells, damage that kills). A sacrificed creature 'dies' but is not 'destroyed.'"},
{q:"What does 'until end of turn' mean?",a:"Temporary effects that last 'until end of turn' or 'this turn' expire during the cleanup step at the end of the turn, after the active player discards to maximum hand size. These effects disappear without using the stack."},
{q:"What is 'sacrifice' in MTG?",a:"To sacrifice a permanent, its controller moves it from the battlefield to the graveyard. Sacrificed permanents cannot be regenerated, cannot be saved by indestructible, and don't trigger 'when destroyed.' They do trigger 'when this creature dies.'"},
{q:"Can an indestructible creature be exiled?",a:"Yes. Indestructible only protects from being destroyed (by damage or 'destroy' effects). It does not protect from being exiled, bounced to hand, returned to library, or reduced to 0 toughness by -1/-1 effects."},
{q:"What is 'bolster'?",a:"Bolster N means: identify the creature you control with the least toughness, then put N +1/+1 counters on it. If multiple creatures are tied for least toughness, you choose which one gets the counters."},
{q:"What is populate?",a:"Populate means: choose a creature token you control and create a copy of it. If you control no creature tokens, populate does nothing."},
{q:"What happens when a creature with an aura dies?",a:"When a creature leaves the battlefield, any auras attached to it are put into their owners' graveyards. This happens as a state-based action. Enchantments attached to lands/artifacts follow the same rule."},
{q:"Can you put counters on an opponent's creature?",a:"Yes, unless the spell or ability specifies 'you control.' Cards like Generous Gift can target any creature. Giving an opponent's creature +1/+1 counters is legal unless the card restricts who controls the target."},
{q:"What is the 'City's Blessing'?",a:"Ascend cards reference 'the city's blessing.' You get the city's blessing as soon as you control 10 or more permanents (checked at any time, not just when ascend triggers). Once you have the city's blessing, you keep it for the rest of the game even if you lose permanents."},

// ============================================================
// FORMAT-SPECIFIC RULES
// ============================================================
{q:"What are the banned cards in Standard?",a:"Standard bans rotate with sets. Check the official MTG website for the current Standard banned list. Notably, cards that have been banned include Fable of the Mirror-Breaker, The Meathook Massacre, and others. Always verify with current Wizards announcements."},
{q:"What is the Commander ban list?",a:"Commander has its own ban list maintained by the Commander Rules Committee. Notably banned: Braids (Cabal Minion), Coalition Victory, Emrakul (the Aeons Torn), Golos, Griselbrand, Prophet of Kruphix, Rofellos, Sundering Titan, Sway of the Stars, Sylvan Primordial, Iona, Leovold, Limited Resources, Lutri (as companion), Panoptic Mirror, Primeval Titan, Recurring Nightmare, Sundering Titan, Trade Secrets, Upheaval, Worldfire."},
{q:"What is the Modern ban list?",a:"Notable Modern bans include: Ancient Den and other artifact lands, Birthing Pod, Blazing Shoal, Cloudpost, Dark Depths, Deathrite Shaman, Eye of Ugin, Gitaxian Probe, Golgari Grave-Troll, Green Sun's Zenith, Hogaak, Krark-Clan Ironworks, Mental Misstep, Mycosynth Lattice (unbanned), Oko Thief of Crowns, Once Upon a Time, Ponder, Preordain, Punishing Fire, Rite of Flame, Second Sunrise, Seething Song, Sensei's Divining Top, Splinter Twin, Summer Bloom, Treasure Cruise. Always verify current list with Wizards."},
{q:"What is the Legacy ban list?",a:"Legacy allows almost all cards except: Black Lotus, Moxen, Time Walk, Time Vault, Library of Alexandria, Ancestral Recall, and other Power Nine, plus specific broken combos. Full list available at MTG official site. Notably the Power Nine are all banned in Legacy and below."},
{q:"What is the difference between Modern and Legacy?",a:"Modern allows sets from Eighth Edition / Mirrodin (2003) onward. Legacy allows cards from all sets except those on the Legacy banned list. Legacy has a much wider card pool and lower mana-cost plays due to more powerful land bases and broken spells."},
{q:"What is the 50-card sideboard in Vintage?",a:"In Vintage, your sideboard is 15 cards (like other formats). However, Vintage has a Restricted list instead of a ban list — restricted cards are limited to 1 copy in your deck and sideboard combined."},
{q:"How does Draft work?",a:"Each player opens a booster pack, picks one card, and passes the remaining cards to the next player. Repeat until all cards are picked. Then open a second pack, pass in the opposite direction. Third pack, back to the original direction. After drafting, build a 40-card deck using your picks and as many basic lands as you want."},
{q:"What is a companion in MTG?",a:"Companions are cards in your sideboard with a special restriction. Before the game, you may reveal your companion if your deck meets its condition. Once per game, you can pay 3 generic mana to move it from outside the game to your hand. It then works like a normal card."},
{q:"What is the rule of 9 in Commander?",a:"Not an official rule, but common wisdom: since you draw ~60 cards in a Commander game, running 9 copies of an effect (e.g. 9 ramp spells, 9 draw spells, 9 removal spells) gives you a good chance of seeing one early. It's a deckbuilding heuristic, not an official rule."},

// ============================================================
// PLANESWALKERS
// ============================================================
{q:"Can two players control the same planeswalker?",a:"Yes. The old 'planeswalker uniqueness rule' was removed. Now the legend rule applies to planeswalkers just like creatures — you can't control two planeswalkers with the same name, but two different players can each control a copy of the same planeswalker."},
{q:"Can you attack a planeswalker with your creatures?",a:"Yes. When declaring attackers, you choose whether each creature attacks a player or a planeswalker that player controls. Damage dealt to a planeswalker removes loyalty counters. Trample damage can go to the planeswalker if blocking creatures don't absorb it all."},
{q:"Can planeswalkers be killed by spells?",a:"Yes. Planeswalkers can be targeted by removal spells that say 'target permanent,' 'target planeswalker,' etc. Spells like Lightning Bolt that target only creatures cannot target planeswalkers unless the text says 'any target.'"},
{q:"What does 'any target' mean?",a:"'Any target' means the spell can target a player, planeswalker, or creature. Lightning Bolt was errata'd to say 'any target' so it can target planeswalkers and players. Spells that say 'target creature' can only target creatures."},

// ============================================================
// REPLACEMENT EFFECTS
// ============================================================
{q:"What is a replacement effect?",a:"A replacement effect modifies how an event would happen. It uses the word 'instead' or 'as' (as in 'as this creature enters the battlefield'). Replacement effects don't use the stack — they modify events as they happen. You can't respond to a replacement effect."},
{q:"What is a prevention effect?",a:"Prevention effects stop damage from being dealt. 'Prevent the next N damage' effects are replacement effects — the damage doesn't happen in the first place. Damage prevention shields are used in order of the controller's choice."},
{q:"What happens when multiple replacement effects apply?",a:"The affected player (or controller of the permanent) chooses which replacement effect applies first. After one applies, check if any others still apply to the modified event. For example, multiple 'if would die, exile instead' effects — the player/controller chooses which applies."},

// ============================================================
// COMMON RULINGS
// ============================================================
{q:"Does Sol Ring tap for 2?",a:"Sol Ring taps for 2 colorless mana. It costs 1 generic mana to cast. It's one of the strongest mana rocks in the game and is banned or restricted in most formats — legal in Commander, Legacy (restricted in Vintage, banned in others)."},
{q:"How does Cyclonic Rift work?",a:"Cyclonic Rift returns target nonland permanent to its owner's hand for 2 mana. For 7 mana (overloaded), it returns ALL nonland permanents opponents control to their owners' hands. This includes tokens (which then cease to exist), creatures, enchantments, artifacts, and planeswalkers."},
{q:"How does Counterspell work?",a:"Counterspell counters target spell — it goes to the graveyard without resolving. It costs UU (2 blue mana). It's a hard counter with no conditions. Note: it cannot counter spells with split second; those cannot be responded to with non-mana abilities."},
{q:"Does Lightning Bolt kill a 4/4?",a:"No. Lightning Bolt deals 3 damage. A 4/4 creature has 4 toughness — it needs 4 damage to die from a single source. 3 damage would reduce it to a 4/1 (for the turn) with 3 damage marked on it, but it won't die unless the total damage from all sources equals or exceeds its toughness."},
{q:"How does Rhystic Study work?",a:"Rhystic Study triggers whenever an opponent casts a spell. That opponent may pay 1 mana. If they don't, you draw a card. The trigger goes on the stack after the opponent's spell is cast, and both the study trigger and the original spell are on the stack — the opponent can't 'go back' and pay after you draw."},
{q:"How does Smothering Tithe work?",a:"Smothering Tithe triggers whenever an opponent draws a card. That opponent may pay 2 mana. If they don't, you create a Treasure token. In Commander, this triggers every time any opponent draws — including at the start of their turn and from card draw effects."},
{q:"How does Demonic Tutor work?",a:"Demonic Tutor (sorcery, 1B) lets you search your library for any card, put it into your hand, then shuffle. No conditions, no reveals. It's banned in Standard, Modern, Legacy, and Pioneer — legal only in Vintage (restricted to 1) and Commander."},
{q:"How does Path to Exile work?",a:"Path to Exile exiles target creature. Its controller may search their library for a basic land and put it onto the battlefield tapped, then shuffle. The land search is optional — opponents may choose not to search (e.g. if you're using it on your own creature)."},
{q:"How does Swords to Plowshares work?",a:"Swords to Plowshares exiles target creature. Its controller gains life equal to the creature's power. This is a replacement — the creature goes to exile, not the graveyard, so reanimation doesn't work on it. The life gain is mandatory for the creature's controller."},
{q:"How does Wrath of God work?",a:"Wrath of God destroys all creatures. They cannot be regenerated (unlike Damnation which just says destroy). Indestructible creatures survive Wrath of God. Tokens are destroyed but instead of going to the graveyard, cease to exist."},
{q:"Does Doomsday win the game?",a:"Doomsday (BBB, sorcery) lets you search your library, graveyard, and hand, choose 5 cards, shuffle the rest into your library, then put those 5 cards on top in any order. This is used in combo decks to set up a 5-card win pile to be drawn and played in sequence."},
{q:"How does Blood Moon work?",a:"Blood Moon is an enchantment that makes all nonbasic lands become mountains. This means they only tap for red mana and lose all other abilities (including tapping for other colors). Basic lands are unaffected. Lands that enter after Blood Moon is in play are also affected."},
{q:"How does Teferi, Time Raveler work?",a:"Teferi, Time Raveler (2WU, planeswalker) has 3 loyalty and 3 abilities: +1 lets you cast sorceries as though they had flash; -3 returns target spell or nonland permanent to its owner's hand; static ability: each opponent can only cast spells at times they could cast a sorcery (their main phase, stack empty). This is extremely powerful control."},
{q:"How does Command Tower work?",a:"Command Tower is a Commander staple land that taps to add one mana of any color in your commander's color identity. In a 2-color deck it taps for either color; in a 5-color deck it taps for any of the 5 colors. It produces no mana if your commander is colorless."},
{q:"How does Seedborn Muse work?",a:"Seedborn Muse untaps all permanents you control during each other player's untap step. In Commander, this means your lands and creatures untap 3 times between your turns — giving you effectively 4x your mana across a full round."},
{q:"How does Aura Shards work?",a:"Aura Shards triggers whenever a creature enters the battlefield under your control. You may destroy target artifact or enchantment. It stacks — if multiple creatures enter at once (e.g. mass token creation), each one triggers separately."},
{q:"How does Ponder work?",a:"Ponder (U, sorcery) lets you look at the top 3 cards of your library, arrange them in any order, then draw a card (from the top). Optionally, you may shuffle your library first and then draw. Ponder is banned in Modern and Legacy restricted in Vintage for being too powerful for 1 mana."},
{q:"How does Brainstorm work?",a:"Brainstorm (U, instant) draws 3 cards, then puts 2 cards from your hand on top of your library in any order. It's best with shuffle effects (fetchlands) to avoid bricking yourself with the 2 put-back cards. It's restricted in Vintage and banned in Legacy (wait — Brainstorm is NOT banned in Legacy; it's one of Legacy's defining cards and legal at 4 copies)."},
{q:"How does Dark Confidant work?",a:"Dark Confidant (1B, 2/1) triggers at the beginning of your upkeep: reveal the top card of your library, put it in your hand, and lose life equal to its mana value. Free card draw with a life cost — very powerful in low-curve decks, very risky in high-curve decks."},
{q:"How does Snapcaster Mage work?",a:"Snapcaster Mage (1U, 2/1) has flash and ETB: target instant or sorcery in your graveyard gains flashback until end of turn, with flashback cost equal to its mana cost. You can then cast the targeted card from your graveyard and exile it. Snapcaster itself resolves first before you can use the flashback."},
{q:"How does fetchland work?",a:"Fetchlands (Flooded Strand, Polluted Delta, etc.) tap and pay 1 life: search your library for a basic land or a land of the specified types, put it onto the battlefield (tapped for most fetches), then shuffle your library. They're used for mana fixing, shuffling after Brainstorm, and thinning your deck."}
];

// ============================================================
// ADDITIONAL RULINGS - KEYWORDS & MECHANICS
// ============================================================
MTG_RULES.push(
{q:"What is proliferate?",a:"Proliferate means: choose any number of players and/or permanents that have counters on them, then give each one more counter of each kind already on them. This includes loyalty counters on planeswalkers, charge counters, +1/+1 counters, poison counters, and even -1/-1 counters."},
{q:"What is toxic?",a:"Toxic N means: whenever this creature deals combat damage to a player, that player gets N poison counters. Toxic stacks with infect — a creature with both gives poison counters equal to the combined value. A player with 10 or more poison counters loses the game."},
{q:"What is infect?",a:"Infect deals damage to players in the form of poison counters instead of life loss, and to creatures in the form of -1/-1 counters instead of damage. A player with 10 or more poison counters loses. Infect damage to creatures uses -1/-1 counters, which persist after the turn ends."},
{q:"What is wither?",a:"Wither deals damage to creatures in the form of -1/-1 counters instead of damage. Unlike infect, wither still deals normal damage to players. The -1/-1 counters remain on the creature permanently until removed."},
{q:"What is exalted?",a:"Exalted triggers whenever a creature you control attacks alone. That creature gets +1/+1 until end of turn for each instance of exalted among permanents you control. Multiple exalted abilities all trigger separately."},
{q:"What is annihilator?",a:"Annihilator N is a triggered ability on Eldrazi. Whenever a creature with annihilator attacks, the defending player sacrifices N permanents. This happens before blockers are declared — the defender chooses what to sacrifice. It cannot be prevented, only redirected by changing attackers."},
{q:"What is affinity?",a:"Affinity for artifacts means: this spell costs 1 less to cast for each artifact you control. Affinity for basic land types works similarly. The reduction applies to the generic mana portion of the cost only — it can't reduce below 0."},
{q:"What is metalcraft?",a:"Metalcraft is a conditional ability that grants a bonus if you control three or more artifacts. It's checked at the time the ability is triggered or the spell is cast — not continuously. Losing artifacts after resolving a metalcraft effect doesn't undo the bonus."},
{q:"What is threshold?",a:"Threshold is a conditional ability that grants a bonus if you have seven or more cards in your graveyard. Like metalcraft, it's a static ability checked continuously — if your graveyard drops below 7, you lose the bonus."},
{q:"What is madness?",a:"Madness is an alternative cost. When you discard a card with madness, you exile it instead of putting it in the graveyard, then you may cast it from exile for its madness cost. If you don't cast it, it goes to the graveyard. Madness lets you discard at instant speed with looting effects."},
{q:"What is delve?",a:"Delve lets you exile cards from your graveyard to help pay for a spell. Each exiled card reduces the generic mana cost by 1. Delve is why Treasure Cruise and Dig Through Time were banned in Modern and restricted in Legacy/Vintage."},
{q:"What is dredge?",a:"Dredge N is a replacement effect. Instead of drawing a card, you may mill N cards and return the dredge card from your graveyard to your hand. It replaces the draw entirely — you can't draw AND dredge. Dredge is very powerful for filling graveyards quickly."},
{q:"What is undying?",a:"When a creature with undying dies (goes to the graveyard from the battlefield), if it had no +1/+1 counters on it, it returns to the battlefield under its owner's control with a +1/+1 counter. Undying only triggers once per death — the +1/+1 counter prevents it from triggering again."},
{q:"What is persist?",a:"When a creature with persist dies, if it had no -1/-1 counters on it, it returns to the battlefield under its owner's control with a -1/-1 counter. Persist works once per death. Persist and undying interact — if a creature has both (e.g. via an effect), the rules specify which triggers."},
{q:"What is modular?",a:"Modular N means: this artifact creature enters the battlefield with N +1/+1 counters. When it dies, you may move all +1/+1 counters from it to target artifact creature. The counters transfer, not the card."},
{q:"What is equip?",a:"Equip is an activated ability of Equipment artifacts. Pay the equip cost: attach this Equipment to target creature you control. Equip can only target creatures you control and can only be activated at sorcery speed (main phase, stack empty)."},
{q:"What is attach?",a:"Some effects say 'attach' an aura or equipment to a permanent. Attaching doesn't target — it bypasses hexproof and shroud. Auras attached via 'put onto the battlefield' also don't target. Only when you cast an aura from hand does it target."},
{q:"What is fortify?",a:"Fortify is to Fortification artifacts what Equip is to Equipment. Pay the fortify cost: attach this Fortification to target land you control. Fortification artifacts attach to lands rather than creatures."},
{q:"What is ninjutsu?",a:"Ninjutsu is an activated ability. Return an unblocked attacker you control to its owner's hand: put the ninja card from your hand onto the battlefield tapped and attacking. The ninja enters attacking but the defending player can't add new blockers after the ninja enters."},
{q:"What is bushido?",a:"Bushido N means: whenever this creature blocks or becomes blocked, it gets +N/+N until end of turn. Bushido is a keyword from Kamigawa that grants a combat bonus to samurai creatures."},
{q:"What is soulshift?",a:"When a creature with soulshift N dies, you may return target Spirit card with mana value N or less from your graveyard to your hand. It's a triggered death effect from the original Kamigawa block."},
{q:"What is splice onto arcane?",a:"When you cast an Arcane spell, you may reveal a card with splice onto arcane and pay its splice cost. The spliced card's text is added to the Arcane spell. The spliced card stays in your hand — only its text is added to the spell being cast."},
{q:"What is prowl?",a:"Prowl is an alternative cost. You may cast a spell for its prowl cost if you dealt combat damage to a player this turn with a creature that shares a creature type with that card. Prowling doesn't count as 'casting for its mana cost.'"},
{q:"What is retrace?",a:"Retrace is an alternative cost. You may cast a card with retrace from your graveyard by paying its mana cost and discarding a land card. Each use puts the card in the graveyard again after resolving."},
{q:"What is overload?",a:"Overload is an alternative cost. If you pay the overload cost, the spell's text changes — all instances of 'target' become 'each.' For example, Mizzium Mortars with overload deals 4 damage to each non-Wizard creature opponents control."},
{q:"What is cipher?",a:"Cipher lets you encode a spell onto a creature you control after casting it. The encoded spell is exiled, and the creature it's encoded on gains 'whenever this creature deals combat damage to a player, you may copy the encoded card and cast the copy for free.'"},
{q:"What is bestow?",a:"Bestow is an alternative cost. When cast for its bestow cost, the card is an Aura Enchantment — Aura. If the creature it's attached to dies, the bestow card becomes a creature with its own power/toughness instead of going to the graveyard."},
{q:"What is tribute?",a:"Tribute N means: as a creature with tribute enters the battlefield, an opponent may put N +1/+1 counters on it. The creature has two different versions of its ETB trigger — one if tribute was paid (opponent chose to give counters), one if it wasn't."},
{q:"What is inspired?",a:"Inspired triggers whenever the creature with inspired becomes untapped. Usually used with ways to tap your own creatures (attack, tap abilities, others' spells). The trigger goes on the stack when it untaps."},
{q:"What is constellation?",a:"Constellation triggers whenever an enchantment enters the battlefield under your control, including the enchantment with constellation itself. Multiple constellation abilities each trigger separately."},
{q:"What is formidable?",a:"Formidable is a conditional ability that functions if creatures you control have total power 8 or more. It's usually on activated or triggered abilities that become available once that power threshold is met."},
{q:"What is exploit?",a:"Exploit triggers when a creature with exploit enters the battlefield. You may sacrifice a creature. If you do, the exploit ability triggers with an additional effect. Sacrificing is optional — you choose at resolution."},
{q:"What is renown?",a:"Renown N means: when this creature deals combat damage to a player, if it isn't renowned, put N +1/+1 counters on it and it becomes renowned. Renowned is a designation tracked on the creature — once it's renowned, renown won't trigger again."},
{q:"What is surge?",a:"Surge is an alternative cost. You may cast a spell for its surge cost if you or a teammate has cast another spell this turn. The surge cost is usually cheaper than the regular cost."},
{q:"What is meld?",a:"Meld is a special transform mechanic. Two specific cards meld together if both are on the battlefield and specific conditions are met. Turn them over and combine them into one oversized card (the meld card). The combined card is one permanent with all the meld card's characteristics."},
{q:"What is skulk?",a:"Skulk means: this creature can't be blocked by creatures with greater power. So a 1/1 with skulk can only be blocked by other 1-power creatures. Increasing the skulk creature's power allows larger creatures to block it."},
{q:"What is emerge?",a:"Emerge is an alternative cost. You may cast a spell for its emerge cost minus the mana value of a creature you sacrifice as you cast it. The sacrificed creature's mana value reduces the generic mana portion of the emerge cost."},
{q:"What is escalate?",a:"Escalate is an additional cost for modal spells (choose one/two/three modes). You pay the escalate cost for each mode beyond the first. Paying all modes of a Choose Three spell requires paying escalate twice."},
{q:"What is myriad?",a:"Myriad triggers whenever a creature with myriad attacks. For each other opponent, you create a tapped and attacking token copy of that creature attacking that opponent (or one of their planeswalkers). The tokens are exiled at end of combat."},
{q:"What is crew?",a:"Crew N is an activated ability of Vehicle artifacts. Tap any number of creatures you control with total power N or greater: this Vehicle becomes an artifact creature until end of turn. Tapping creatures to crew doesn't use the stack."},
{q:"What is fabricate?",a:"Fabricate N triggers when the creature with fabricate enters the battlefield. You choose: put N +1/+1 counters on it OR create N 1/1 colorless Servo artifact creature tokens. You make the choice at resolution."},
{q:"What is energy counters?",a:"Energy counters ({E}) are a resource stored on players (not permanents). Certain cards produce energy and other cards let you spend energy for effects. Energy counters don't reset between turns and can accumulate indefinitely."},
{q:"What is revolt?",a:"Revolt is a conditional ability that functions if a permanent you controlled left the battlefield this turn. It's typically checked at the time the spell resolves or the ability triggers, not continuously."},
{q:"What is embalm?",a:"Embalm is an activated ability you can use only if the card is in your graveyard. Pay the embalm cost and exile the card: create a token that's a copy of it, except it's white, has no mana cost, and is a Zombie in addition to its other types. Embalm can only be used once (the card is exiled)."},
{q:"What is eternalize?",a:"Eternalize works like embalm but creates a 4/4 black Zombie token copy of the card (regardless of original stats) and exiles the original. The token has no mana cost and is black in addition to other colors."},
{q:"What is aftermath?",a:"Aftermath is a split card mechanic. The aftermath half can only be cast from the graveyard (and is exiled after). The left half is cast normally from hand. Each half has a different casting restriction."},
{q:"What is enrage?",a:"Enrage is a triggered ability that triggers whenever the creature with enrage is dealt damage. This can be triggered by damage from spells, abilities, combat damage, or even your own effects. Enrage triggers once per damage event, not once per point of damage."},
{q:"What is raid?",a:"Raid is a conditional ability that functions if you attacked with a creature this turn. Some raid effects require you to have attacked to activate or trigger; others only provide a bonus if the raid condition is met."},
{q:"What is explore?",a:"Explore means: reveal the top card of your library. If it's a land, put it into your hand. Otherwise, put a +1/+1 counter on the exploring creature and either keep the card on top or put it in the graveyard. Explore is an action that happens once when instructed."},
{q:"What is ascend?",a:"Ascend grants 'the city's blessing' — a permanent designation — to a player who controls 10 or more permanents. Once you have the city's blessing, you keep it for the rest of the game regardless of how many permanents you control later."},
{q:"What is jump-start?",a:"Jump-start is an alternative cost. You may cast a card with jump-start from your graveyard by paying its mana cost and discarding a card. The jump-start card is exiled when it resolves or leaves the stack. Unlike retrace, you discard any card, not just a land."},
{q:"What is mentor?",a:"Mentor triggers whenever a creature with mentor attacks. Put a +1/+1 counter on target attacking creature with lesser power. The mentored creature must have less power than the mentor at the time of resolution."},
{q:"What is spectacle?",a:"Spectacle is an alternative cost. You may cast a spell for its spectacle cost if an opponent lost life this turn. Spectacle costs are usually cheaper than the regular cost."},
{q:"What is undergrowth?",a:"Undergrowth is a conditional ability that counts creature cards in your graveyard. Various effects scale with the number of creature cards in your graveyard at the time of casting or resolution."},
{q:"What is riot?",a:"Riot triggers when a creature with riot enters the battlefield. You choose: put a +1/+1 counter on it OR give it haste until end of turn. If the creature has multiple instances of riot, each one lets you choose separately."},
{q:"What is addendum?",a:"Addendum is a conditional ability on instants. The spell has an additional effect if you cast it during your main phase (as opposed to during combat or an opponent's turn). Addendum is checked at cast time."},
{q:"What is amass?",a:"Amass N means: if you don't control an Army token, create a 0/0 black Zombie Army token. Then put N +1/+1 counters on your Army. All amass effects add to the same Army token — you only ever have one Army."},
{q:"What is proliferate with counters?",a:"Proliferate lets you add counters of any type already present. This includes loyalty counters (beneficial), charge counters on artifacts, +1/+1 counters on creatures, and even -1/-1 counters or poison counters on opponents. You choose which players/permanents to proliferate and of which counter types."},
{q:"What is mutate targeting?",a:"Mutate targets a non-Human creature you control. If the creature is an illegal target when mutate tries to resolve (e.g. it gained protection or hexproof after targeting), the mutate spell is countered and goes to the graveyard. The creature you targeted doesn't get any effect."},
{q:"What is party in MTG?",a:"Party is a mechanic counting characters in your party: up to one each of Cleric, Rogue, Warrior, and Wizard. Your party size is the number of these types you have (max 4). Cards reference 'a full party' (4 creatures of all four types) or 'your party' (current count)."},
{q:"What is foretell timing?",a:"You may foretell a card during your turn by paying 2 and exiling it face-down. On future turns, you may cast it for its foretell cost as a sorcery (main phase, stack empty) or at instant speed if it's an instant or has flash. The foretell cost is usually cheaper than the normal casting cost."},
{q:"What is boast?",a:"Boast is an activated ability you can activate only once per turn, and only if the creature with boast attacked this turn. Pay the boast cost to get an effect. You must have declared the creature as an attacker that same turn."},
{q:"What is disturb?",a:"Disturb is an alternative cost allowing you to cast a card from your graveyard transformed (its back face). The disturb cost is paid to cast the back face from the graveyard. If the disturbed permanent would go to the graveyard, it's exiled instead."},
{q:"What is daybound and nightbound?",a:"Daybound and nightbound are transform conditions. It becomes night if an active player cast no spells during their turn. It becomes day if an active player casts two or more spells during their turn. Permanents with daybound transform at night; nightbound transform at day."},
{q:"What is decayed?",a:"Decayed is a condition on Zombie tokens. A creature with decayed can't block, and when it attacks, sacrifice it at end of combat. Decayed is meant to represent expendable zombie hordes."},
{q:"What is training?",a:"Training triggers whenever a creature with training attacks alongside a creature with greater power. Put a +1/+1 counter on the training creature. If the greater-power creature leaves the battlefield before training resolves, training still resolves if the condition was met when it triggered."},
{q:"What is blitz?",a:"Blitz is an alternative cost. If you cast a creature for its blitz cost, it gains haste and 'when this creature dies, draw a card.' At the beginning of the next end step, sacrifice it. Blitz creates a temporary aggressive creature with card draw on death."},
{q:"What is casualty cost?",a:"Casualty N is an optional additional cost. As you cast the spell, you may sacrifice a creature with power N or greater. If you do, you copy the spell (choosing new targets if needed). The original spell and the copy both go on the stack."},
{q:"What is connive?",a:"Connive means: draw a card, then discard a card. If you discarded a nonland card, put a +1/+1 counter on the conniving creature. Conniving lets you loot through your deck while growing your creatures."},
{q:"What is alliance?",a:"Alliance triggers whenever another creature enters the battlefield under your control. Multiple alliance abilities each trigger separately, so multiple creatures entering at once (with the same controller) trigger multiple alliance abilities."},
{q:"What is backup?",a:"Backup N means: when this creature enters the battlefield, put N +1/+1 counters on target creature. If that target is another creature, it temporarily gains all abilities of the backup creature until end of turn (in addition to the counters)."},
{q:"What is read ahead?",a:"Read Ahead is a keyword on Sagas. Instead of starting at Chapter I, you may choose any chapter number and place that many lore counters on the Saga when it enters the battlefield. The Saga skips earlier chapters and starts at the chosen chapter."},
{q:"What is prototype?",a:"Prototype is an alternative cost on artifact creatures. If you cast a card for its prototype cost, it becomes a smaller version with different power/toughness and different color. When the prototype permanent would die, you may instead put it in the graveyard as the full-cost version."},
{q:"What is unearth?",a:"Unearth is an activated ability you can use only if the card is in your graveyard. Pay the unearth cost: return the creature to the battlefield. It gains haste. Exile it at the beginning of the next end step or if it would leave the battlefield. Unearth cards can't be reused."},
{q:"What is ninjutsu with no creatures?",a:"Ninjutsu can only be used when you have an unblocked attacking creature. You return the unblocked attacker to your hand and put the ninja in. If all your attackers are blocked, you cannot use ninjutsu. The attacking player must choose to use ninjutsu after blockers are declared but before combat damage."},

// ============================================================
// COMMON INTERACTIONS
// ============================================================
{q:"Does a counterspell counter an activated ability?",a:"No. 'Counterspell' and most counterspells say 'counter target spell.' Activated and triggered abilities are NOT spells — they use the stack but aren't spells. To counter an ability, you need a specific card that says 'counter target activated ability' or 'counter target ability' (like Stifle or Tale's End)."},
{q:"Can you respond to a planeswalker loyalty ability?",a:"Yes. Loyalty abilities go on the stack when activated and can be responded to. However, the loyalty change (+ or -) is part of the cost paid when activating, not the effect. If the ability is countered, the loyalty is already spent."},
{q:"Does graveyard hate stop escape?",a:"Yes. If you exile the escape card's graveyard before the escape spell is cast, it can't be cast via escape. Rest in Peace, Leyline of the Void, and similar effects that exile graveyards permanently prevent escape, dredge, flashback, etc."},
{q:"Can you use a land's ability the same turn it enters?",a:"Yes. Tapping a land for mana is a mana ability and doesn't have summoning sickness restrictions. Only creatures have summoning sickness. However, a land with a non-mana tap ability (like Maze of Ith) can't tap for that ability the turn it enters if it has summoning sickness... wait — lands don't have summoning sickness. Any land can tap for any ability the turn it enters, unless it enters tapped."},
{q:"Does doubling season affect planeswalker loyalty?",a:"Yes. Doubling Season says if an effect would put one or more counters on a permanent you control, put twice that many instead. Planeswalkers enter with loyalty counters, so they enter with double loyalty under Doubling Season. This also means + abilities add double the loyalty. However, loyalty costs to activate abilities are costs, not effects — so - abilities still cost their normal amount."},
{q:"Can a creature block while tapped?",a:"No. Tapped creatures can't block. Only untapped creatures in the declare blockers step can be declared as blockers. If a creature gets tapped after blockers are declared, the blocked/unblocked status doesn't change."},
{q:"Does deathtouch work on trample damage?",a:"Yes. With deathtouch and trample, you only need to assign 1 damage to each blocker (since any amount is lethal), and the rest can trample through. A 6/6 deathtouch trample attacking into a 5/5 blocker only needs to assign 1 damage to the blocker, leaving 5 to trample through."},
{q:"Can you sacrifice a creature in response to a removal spell targeting it?",a:"Yes. When a spell targets your creature, you receive priority before the spell resolves. You can sacrifice the creature in response (if you have a sacrifice outlet). The removal spell then tries to resolve but has no legal target and is countered (if targeting) or fizzles."},
{q:"Can you stack multiple triggered abilities from the same creature?",a:"Yes. If multiple triggers happen simultaneously from the same source, they're all put on the stack. The active player orders their triggers, then the non-active player orders theirs. Each trigger resolves separately."},
{q:"Does flying work against islandwalk?",a:"Landwalk (islandwalk, mountainwalk, etc.) means the creature is unblockable if the defending player controls a land of that type. Flying is irrelevant — a creature with flying can't block a landwalking creature if the defending player has the relevant land. Reach doesn't help against landwalk."},
{q:"Can you copy a spell with no targets?",a:"Yes. You can copy any instant or sorcery spell on the stack, including those without targets. Cards like Twincast or Dual Casting can copy a spell like Wrath of God or Cultivate with no issue. When you copy, you may choose new targets for the copy."},
{q:"What happens when a permanent is bounced with an aura on it?",a:"When a permanent returns to its owner's hand, any auras attached to it go to the graveyard (state-based action). Equipment stays on the battlefield — it becomes unattached but doesn't go anywhere."},
{q:"Can you regenerate an indestructible creature?",a:"You can activate regeneration on an indestructible creature, but it won't do anything extra since the creature can't be destroyed anyway. The regeneration shield is wasted but doesn't cause any problem. Regeneration is also useless against exile, sacrifice, and toughness reduction."},
{q:"Does lifelink work with damage to planeswalkers?",a:"Yes. If a creature with lifelink deals combat damage to a planeswalker, the controller of the lifelink creature gains life equal to the damage dealt. The damage removes loyalty from the planeswalker and simultaneously grants life."},
{q:"Can you cast a spell during your opponent's turn?",a:"You can cast instants and spells/abilities with flash during any player's turn, any time you have priority. You cannot cast sorceries, creatures (without flash), enchantments, artifacts, or planeswalkers during your opponent's turn."},
{q:"What is split damage in a block?",a:"When multiple creatures block a single attacker, the attacking player assigns damage to the blockers in an order of their choice, but must assign lethal damage to each blocker before moving to the next (unless the attacker has trample). The attacker chooses the order of damage assignment."},
{q:"Can you pay life if you have 0 life?",a:"Yes, in most cases. You can pay life costs even if you have 0 or fewer life — for example, paying life for Phyrexian mana or Gitaxian Probe. However, the moment a player has 0 or fewer life, they lose as a state-based action. So paying life at 1 causes you to lose immediately after."},
{q:"Does 'draw a card' trigger Rhystic Study?",a:"No. Rhystic Study triggers when an opponent casts a spell. Drawing a card is not casting a spell — it doesn't trigger Rhystic Study. Cards that trigger on draw are separately worded (like Consecrated Sphinx)."},
{q:"What is storm?",a:"Storm triggers when you cast a spell. Copy the spell for each other spell cast before it this turn. Each player may choose new targets for each copy. Storm counts ALL spells cast this turn, not just your own. Storm is banned in most formats except Legacy and Vintage."},
{q:"Can you return an exiled card with graveyard recursion?",a:"No. Cards in exile are not in the graveyard. Effects like Reanimate, Eternal Witness, and Unearth only work on graveyard cards. You need specific 'exile recursion' effects to return cards from exile. Once exiled by most effects, cards stay exiled permanently."},
{q:"What is the difference between 'return to hand' and 'put into hand'?",a:"Both mean the card ends up in the owner's hand, but 'return to hand' is a bounce effect that targets and can be responded to. 'Put into hand' is typically a search or tutor effect. Mechanically they work the same — the card goes to hand — but the source and context differ."},
{q:"Does damage happen simultaneously in regular combat?",a:"Yes. In regular combat (no first/double strike), all combat damage is assigned and dealt simultaneously. A 3/3 and 4/4 fighting each other both die — neither 'kills the other first.' First strike creates a separate damage step where first strikers deal damage before regular creatures."},
{q:"Can you activate abilities of a creature with summoning sickness?",a:"A creature with summoning sickness can't attack and can't tap to use abilities with 'tap' in the cost. However, it CAN use activated abilities that don't require it to tap (like sacrifice effects, pay mana effects, or other non-tap costs). Flash creatures with relevant non-tap abilities can be used immediately."},
{q:"What happens if I copy an adventure card?",a:"If you copy the adventure (instant/sorcery) half while casting it, the copy goes on the stack. The copy is NOT exiled — copies never go to exile from the stack. The original adventure goes to exile (where you can cast the creature from), but copies resolve and go to the graveyard."},
{q:"Does a creature that phases out keep its counters?",a:"Yes. When a permanent phases out, it's treated as though it doesn't exist. When it phases back in (usually at the beginning of your next untap step), it returns exactly as it was — with all counters, attached auras, etc. Phasing doesn't trigger 'enters' or 'leaves' triggers."},
{q:"Can you respond to your own spell?",a:"Yes. After you cast a spell, it goes on the stack and you get priority again. You can cast another spell or activate an ability in response to your own spell before it resolves. Both players can interact with each spell on the stack before it resolves."},
{q:"What is a mana ability?",a:"A mana ability is an activated ability or triggered ability that produces mana. Mana abilities don't use the stack and can't be responded to. Examples: tapping a land, Llanowar Elves, Dark Ritual. Distinction: if an ability requires targeting, it's NOT a mana ability (e.g. Selvala's activated ability that requires tapping and a target)."},

// ============================================================
// COMBO RULINGS
// ============================================================
{q:"How does Splinter Twin combo work?",a:"Splinter Twin on Deceiver Exarch (or Pestermite): tap the enchanted creature to create a copy of itself with haste. The copy enters and untaps the original. Tap the original to create another copy. Repeat to create infinite attacking tokens. Attack for lethal. This is why Splinter Twin is banned in Modern."},
{q:"How does Thassa's Oracle win?",a:"Thassa's Oracle (2U, 1/3) has an ETB: look at top X cards of your library where X is your devotion to blue. Put up to one on bottom, rest on top. Also: if your devotion to blue is greater than or equal to the number of cards in your library, you win. The classic combo is Oracle + Demonic Consultation (exile your library, leaving 0 cards) — Oracle's devotion (2) is >= 0 cards in library."},
{q:"How does Underworld Breach combo work?",a:"Underworld Breach gives all cards in your graveyard escape for 3 (pay their cost plus exile 3 cards). The classic combo: Underworld Breach + Brain Freeze + Sol Ring/mana rock. Cast Brain Freeze targeting yourself to fill graveyard, escape it, repeat to exile everyone's library. Most common with a wheel effect."},
{q:"How does Isochron Scepter combo work?",a:"Isochron Scepter imprints an instant with mana value 2 or less. For 2 mana, you can create a copy of the imprinted card and cast it. With Dramatic Reversal (untap all nonland permanents you control) and enough mana rocks producing 3+ mana total, you get infinite mana and infinite casts."},
{q:"How does Grapeshot storm work?",a:"Grapeshot is a storm spell — when cast, it copies itself for each spell cast before it this turn. Ritual spells (Dark Ritual, Pyretic Ritual) each count as spells, so: 5 rituals + Grapeshot = 6 copies of Grapeshot = 6 damage to any targets. Used in Legacy storm decks."},
{q:"How does Ad Nauseam work as a combo?",a:"Ad Nauseam reveals cards from the top of your library one at a time, putting each into your hand and losing life equal to its mana value. With Angel's Grace (or Phyrexian Unlife to prevent losing), you can reveal your entire deck, gaining a massive hand at near-death life total, then win with Lightning Storm or similar."},
{q:"How does Painter's Servant work?",a:"Painter's Servant makes all cards everywhere become the chosen color in addition to their other colors. With Grindstone (tap, 3: target player mills 2, repeat if both are the same color), naming blue with Servant makes every card blue — Grindstone mills the entire library."},
{q:"How does The Locust God combo?",a:"The Locust God creates a 1/1 haste flier whenever you draw a card. With Skullclamp (1, equip 1: equipped creature gets -1/+1; when equipped creature dies, draw 2), equip to a 1/1 Locust Token to kill it and draw 2, creating 2 more tokens, repeat for infinite tokens and draws."},
{q:"How does Food Chain exile work?",a:"Food Chain lets you exile a creature to add mana equal to its mana value +1, but only for creature spells. With Misthollow Griffin (can be cast from exile) or Eternal Scourge, you generate infinite creature-specific mana, then use Squee or similar to convert to spells."},
{q:"How does Craterhoof Behemoth win?",a:"Craterhoof Behemoth ETB gives all creatures you control +X/+X and trample until end of turn, where X is the number of creatures you control. In a token deck with 10+ creatures, this creates a lethal alpha strike from nowhere. Common green Commander finisher."},
{q:"How does Exquisite Blood combo with Sanguine Bond?",a:"Exquisite Blood: whenever an opponent loses life, you gain that much life. Sanguine Bond: whenever you gain life, target opponent loses that much life. Together, any life loss to an opponent triggers an infinite loop — they lose, you gain, they lose, etc. until everyone else is dead."},
{q:"How does Zur the Enchanter work?",a:"Zur attacks and lets you search your library for an Enchantment with mana value 3 or less and put it onto the battlefield. Common targets: Necropotence (pay 1 life draw 1), Diplomatic Immunity (protect Zur), Detention Sphere (exile a permanent), or Omniscience."}
);
