var RULES_OP = [
{t:"Win Conditions",s:"Reduce Life to 0 then land 1 more hit on Leader, or opponent decks out.",e:"Win by: reducing opponent Life cards to 0 AND landing one more unblocked hit on their Leader. Also win if opponent cannot draw a card when required. Each player starts with 5 Life cards. When a player takes a hit with 0 Life remaining they lose immediately."},
{t:"DON!! System",s:"Gain 2 DON per turn. Attach for plus 1000 Power each. Return at Refresh.",e:"Each player has a separate DON!! deck of exactly 10 DON!! cards. Each turn during DON!! Phase gain 2 DON!! from your DON!! deck (first player gains only 1 on their very first turn). DON!! cards can be rested to pay for playing cards OR attached to your Characters or Leader to give plus 1000 Power each. Attached DON!! return to Active DON!! area at start of your Refresh Phase."},
{t:"Turn Structure",s:"Refresh, Draw, DON!!, Main Phase, End Phase.",e:"Refresh Phase: flip all Rested cards to Active position, return all attached DON!! to Active area. Draw Phase: draw 1 card from your deck (first player skips their very first draw). DON!! Phase: gain 2 DON!! from DON!! deck (1 for first player first turn). Main Phase: play cards, attack with Characters and Leader, use effects. End Phase: resolve end of turn effects."},
{t:"Life Cards and Damage",s:"Hit on Leader reveals top Life card. Add to hand. Trigger effects may activate.",e:"When your Leader takes an unblocked hit reveal the top card of your Life pile and add it to your hand. If the revealed card has a Trigger effect you MAY choose to activate it. When your Life pile is completely empty and your Leader takes any unblocked hit you lose the game immediately."},
{t:"Leader Card Rules",s:"Always in play. Cannot be removed. Can attack once per turn.",e:"Your Leader card is always in the Leader Zone and cannot be removed from play by card effects unlike Characters. Your Leader can attack once per turn during your Main Phase. When your Leader attacks it rests (becomes horizontal). Your Leader can also be attacked by opponent units."},
{t:"Attacking with Characters",s:"Active Characters can attack once per turn. They Rest after attacking.",e:"Any Active (upright) Character you control may attack once per turn. After attacking it becomes Rested (horizontal). Characters played this same turn cannot attack unless they have the RUSH keyword. You may attack opponent Rested Characters or attack the opponent Leader directly."},
{t:"Blocking Rules",s:"Rest an Active Character to intercept attack on your Leader.",e:"When your Leader is attacked you may Rest one of your Active Characters to block. The block redirects the attack to that Character. The Character takes the hit: if attacker Power exceeds or equals Character Power the Character is KO and sent to Trash. BLOCKER keyword Characters can also intercept attacks targeting your other Characters not just your Leader."},
{t:"Counter Cards",s:"Discard Counter cards from hand during opponent attack step to boost Power.",e:"During an opponent attack step (after they declare an attack and before damage is resolved) you may discard 1 or more cards with Counter values from your hand. Each discarded Counter card adds its Counter value to your defending Leader or defending Character Power for that battle only. Counter can ONLY be used during the opponent attack step. Choose carefully which cards to discard as they go to Trash."},
{t:"Battle Resolution",s:"Compare attacker Power vs defender Power. Higher survives. Equal means both KO.",e:"After all Counter cards are played compare attacker total Power versus defender total Power. If attacker Power exceeds defender Power: defender is KO and sent to Trash. If defender Power exceeds attacker Power: attacker is KO and sent to Trash. If both have equal Power: both are KO simultaneously."},
{t:"RUSH Keyword",s:"Can attack the turn it is played. Bypasses normal restriction.",e:"Characters with RUSH can attack on the same turn they are played from hand, bypassing the standard rule that newly played Characters cannot attack. RUSH is critical for finishing games and putting immediate pressure on the opponent Life cards."},
{t:"BLOCKER Keyword",s:"Can intercept attacks on your Leader OR your other Characters.",e:"A Character with BLOCKER can intercept attacks targeting your Leader OR any of your other Characters. Must be in Active position to use BLOCKER. After blocking it becomes Rested. A Character can only BLOCK once per turn."},
{t:"TRIGGER Keyword",s:"Activates when this card is revealed from your Life pile as damage.",e:"When a card with TRIGGER is revealed from your Life pile as a result of your Leader taking an unblocked hit, you may activate its Trigger effect. This is a bonus effect for having the card in your Life pile and is entirely separate from playing the card normally. You may choose whether or not to activate Trigger effects."},
{t:"Six Colors",s:"Red aggro, Blue control, Green ramp, Purple restand, Black removal, Yellow life.",e:"Red: aggressive, direct attacks, RUSH effects. Blue: control, bouncing cards, drawing, cost reduction. Green: resource acceleration, cost reduction, searching. Purple: resting and reststanding units, reusing effects. Black: removal effects, KOing opponent units, power reduction. Yellow: Life card manipulation, gaining extra Life, searching from Life pile."},
{t:"DON!! Attachment Strategy",s:"Attach DON!! to boost Power for key battles. Returns at Refresh.",e:"Attaching DON!! to your Leader or Characters gives plus 1000 Power per attached DON!! for the rest of the turn. Attached DON!! return to your Active area at the start of your next Refresh Phase. You cannot use attached DON!! to pay for playing cards. Optimal play often involves attaching multiple DON!! for a decisive attack that claims the final Life card or Leader KO."},
{t:"Rested vs Active",s:"Rested equals horizontal unable to act. Active equals upright and ready.",e:"Active position (upright) means a card is ready to attack, block, or be used as a cost. After attacking, blocking, or being used as a resource cost cards become Rested (horizontal). At the start of your Refresh Phase all your Rested cards including Characters, your Leader, and DON!! all return to Active position simultaneously."},
{t:"Deck Construction",s:"Exactly 50 cards. Max 4 copies per name. 1 Leader. Separate 10 DON!! deck.",e:"Main deck must contain exactly 50 cards. Maximum 4 copies of any card with the same name. 1 Leader card in Leader Zone not counted in 50. Separate DON!! deck of exactly 10 DON!! cards. Cards must match Leader color identity. Dual-color Leaders allow cards of either color."}
];
