var SYNS={
  chain:"chain resolution lifo spell speed chaining respond",
  counter:"counter trap spell speed 3 negate solemn",
  negate:"negation negate activation effect stop cancel",
  mst:"mystical space typhoon quick play destroy chain negate",
  reborn:"monster reborn normal spell resolve summon graveyard",
  destroy:"destroy destruction battle damage chain negate remove",
  typhoon:"mystical space typhoon mst destroy quick play",
  resolve:"chain resolution normal spell field continuous",
  damage:"battle damage calculation formula atk def",
  weakness:"weakness type multiplier times 2 double",
  resistance:"resistance type minus 30 reduce",
  bench:"bench damage weakness resistance spread",
  evolution:"evolve evolution stage rare candy cannot newly",
  retreat:"retreat cost switch condition cure escape rope",
  poison:"poisoned badly poisoned status condition damage counter",
  burn:"burned status condition coin flip damage counter",
  sleep:"asleep status condition coin flip wake sideways",
  para:"paralyzed cannot attack retreat status condition",
  confuse:"confused coin flip self damage upside down",
  gx:"gx attack once per game player total",
  vstar:"vstar power once game marker flip",
  don:"don resource attach power thousand boost",
  life:"life cards leader damage trigger reveal",
  memory:"memory gauge turn ends resource digimon",
  security:"security check reveal effect break attack",
  digivolve:"digivolving stack inherit effects level",
  base:"base hp penetrating damage win gundam",
  burst:"burst card instant any time quick response",
  rush:"rush attack turn deployed cannot wait",
  blocker:"blocker intercept block keyword rest",
  layers:"layers system continuous effects apply order timestamp",
  commander:"commander tax damage color identity edh zone",
  sba:"state-based actions automatic checked toughness",
  protection:"protection debt damage enchant block target",
  indestructible:"indestructible destroy exile sacrifice toughness",
  trample:"trample excess damage player deathtouch",
  extra:"extra deck zone link arrow extra monster zone",
  synchro:"synchro tuner level sum exactly formula",
  xyz:"xyz rank overlay material detach",
  link:"link arrow zone extra deck monster",
  pendulum:"pendulum scale summon between not including",
  fusion:"fusion polymerization material send graveyard",
  ritual:"ritual spell tribute level summon",
  segoc:"segoc simultaneous effects turn player non-turn",
  timing:"timing if when optional mandatory miss",
  cost:"cost semicolon paid activation refunded",
  target:"targeting target declare illegal fizzle",
  honest:"honest hand trap damage step atk",
  sieger:"cyber dragon sieger damage step atk machine",
  veiler:"effect veiler hand trap negate monster main phase",
  ash:"ash blossom hand trap negate search draw special summon",
  nibiru:"nibiru primal being hand trap fifth summon tribute",
  skill:"skill drain continuous trap negate all monsters",
  solemn:"solemn judgment solemn strike counter trap negate",
  infinite:"infinite impermanence trap negate monster column",
  ghost:"ghost ogre snow rabbit hand trap destroy field",
  called:"called by grave banish negate graveyard",
  haste:"haste summoning sickness attack tap turn",
  flash:"flash instant speed cast any time",
  vigilance:"vigilance attacking does not tap",
  lifelink:"lifelink damage life gain simultaneous",
  deathtouch:"deathtouch lethal any damage assign",
  hexproof:"hexproof opponents cannot target you can",
  shroud:"shroud nobody can target controller",
  cascade:"cascade exile cast free mana value",
  infect:"infect poison counter minus minus creature",
  planeswalker:"planeswalker loyalty ability attack",
  priority:"priority pass advance phase respond",
  open:"open game state speed 1 activate",
  flip:"flip summon effect face-down monster",
  spirit:"spirit monster return hand end phase",
  gemini:"gemini monster normal effect second summon",
  toon:"toon monster world direct attack",
  piercing:"piercing defense position damage",
  tribute:"tribute summon level cost send graveyard",
  inheritance:"inherited effects underneath stack digimon",
  tamer:"tamer card digimon field security",
  option:"option card digimon effect trash",
  penetrating:"penetrating damage excess power base gundam",
  flagship:"flagship command zone color identity lose",
  resource:"resource cost deploy gain per turn",
  counter_op:"counter discard hand power boost attack step",
  trigger:"trigger effect when life card reveal",
  prize:"prize card knock out koed won take",
  tool:"tool pokemon attach one per pokemon",
  stadium:"stadium zone one per turn same name",
  ability:"ability pokemon power blocked path peak",
  ace:"ace spec one per deck powerful item",
  radiant:"radiant one per deck no rule box prize",
  prism:"prism star lost zone one per deck",
  lost:"lost zone permanently removed cannot retrieve",
  rarely_candy:"rare candy basic stage 2 skip stage 1",
  breed:"breeding zone digi-egg hatch dp move",
  trash:"trash zone deleted digimon graveyard discard",
  suspend:"suspend unsuspend attack rest digimon"
};
